In [2]:
import numpy as np

In [2]:
a=np.array([2,3,4])
print(a)

[2 3 4]


In [3]:
a=np.array([(2,3,4),(6,5,4)])
print(a)

[[2 3 4]
 [6 5 4]]


In [5]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
b=np.linspace(1,10,5)
b

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [10]:
a=np.array([2,3,4])
a

array([2, 3, 4])

In [41]:
b=np.array([(2,3,4,5),(6,5,4,6),(12,23,24,25)])
b

array([[ 2,  3,  4,  5],
       [ 6,  5,  4,  6],
       [12, 23, 24, 25]])

In [42]:
print(a.ndim)

1


In [43]:
print(b.ndim)

2


In [44]:
print(a.itemsize)

4


In [45]:
print(b.itemsize)

4


In [48]:
print(b.dtype)

int32


In [49]:
print(b.shape)

(3, 4)


In [51]:
b=np.array([(2,3,4,5),(6,5,4,6),(12,23,24,25)])
d=b.reshape(4,3)
d

array([[ 2,  3,  4],
       [ 5,  6,  5],
       [ 4,  6, 12],
       [23, 24, 25]])

In [8]:
b=np.array([(2,3,4,5),(6,5,4,6),(12,23,24,25)])
print(b[1,3])

6


In [10]:
print(b[2:,1])

[23]


In [11]:
a=np.array([34,2,33,55,4,3,66,87,54])
print(a)

[34  2 33 55  4  3 66 87 54]


In [12]:
print(a.max())

87


In [13]:
print(a.min())

2


In [15]:
print(a.sum())

338


In [16]:
a=np.array([2,3,4,5])
b=np.array([5,6,7,8])

In [17]:
print(a+b)

[ 7  9 11 13]


In [18]:
a=np.array([2,3,4,5])
b=np.array([(5,6,7,8),(3,4,5,6)])

In [25]:
print(b.sum(axis=0))

[ 8 10 12 14]


In [28]:
print(np.sqrt(b))

[[2.23606798 2.44948974 2.64575131 2.82842712]
 [1.73205081 2.         2.23606798 2.44948974]]


In [29]:
print(np.exp(a))

[  7.3890561   20.08553692  54.59815003 148.4131591 ]


In [30]:
print(np.log(a))

[0.69314718 1.09861229 1.38629436 1.60943791]


In [31]:
a=np.array([(2,3,4,5),(8,7,6,5)])
b=np.array([(5,6,7,8),(3,4,5,6)])

In [32]:
print(a)

[[2 3 4 5]
 [8 7 6 5]]


In [33]:
print(b)

[[5 6 7 8]
 [3 4 5 6]]


In [39]:
print(np.vstack((a,b)))

[[2 3 4 5]
 [8 7 6 5]
 [5 6 7 8]
 [3 4 5 6]]


In [40]:
print(np.hstack((a,b)))

[[2 3 4 5 5 6 7 8]
 [8 7 6 5 3 4 5 6]]


In [41]:
print(a.ravel())

[2 3 4 5 8 7 6 5]
